CREATE TABLE POLICY_DETAILS(POLICY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
POLICY_NAME VARCHAR(100)
);

CREATE TABLE PARTY_DETAILS(PARTY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
PARTY_NAME VARCHAR(100),
POLICY_ID INT,
CONSTRAINT fk_policy  FOREIGN KEY (POLICY_ID) REFERENCES POLICY_DETAILS (POLICY_ID)
);

CREATE TABLE VEHICLE_DETAILS(VEHICLE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
VEHICLE_NAME VARCHAR(100),
POLICY_ID INT,
CONSTRAINT fk_policy1 FOREIGN KEY (POLICY_ID) REFERENCES POLICY_DETAILS (POLICY_ID)
);



CREATE TABLE ADDRESS_DETAILS(ADDRESS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
CITY VARCHAR(75),
STATE VARCHAR(75),
VEHICLE_ID INT,
CONSTRAINT fk_address FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLE_DETAILS (VEHICLE_ID)
);





select * from ADDRESS_DETAILS;
select * from VEHICLE_DETAILS;
select * from POLICY_DETAILS;
select * from PARTY_DETAILS;



drop table  PARTY_DETAILS;
drop table  ADDRESS_DETAILS;
drop table  VEHICLE_DETAILS;
drop table  POLICY_DETAILS;


CREATE TABLE POLICY_DETAILS(POLICY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
POLICY_NAME VARCHAR(100),
VEHICLE_ID INT
);