CREATE TABLE USERS(USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
FULL_NAME VARCHAR(20),
AGE int,
QUALIFICATION VARCHAR(20), 
GENDER VARCHAR(6),
PASSED_YEAR int
);


CREATE TABLE USERS_ADDRESS(ADDRESS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
ADDRESS_NICK_NAME  VARCHAR(20)  NOT NULL,
USER_ID INT,
CONSTRAINT fk_user  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
) ;

ALTER TABLE USERS_ADDRESS ADD USER_ID INT;
ALTER TABLE USERS_ADDRESS ADD  CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USERS (id);
 
 
CREATE TABLE USERS_ADDRESS_DETAILS(ADDRESS_DETAILS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
STREET_NAME LONG VARCHAR  NOT NULL,
CITY  VARCHAR(50)  NOT NULL,
STATE  VARCHAR(50)  NOT NULL,
ZIP_CODE  VARCHAR(9)  NOT NULL,
ADDRESS_ID INT NOT NULL,
CONSTRAINT fk_address FOREIGN KEY (ADDRESS_ID) REFERENCES USERS_ADDRESS(ADDRESS_ID)  ON DELETE CASCADE ON UPDATE CASCADE
);

