CREATE TABLE ADDRESS_DETAILS(ADDRESS_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
CITY VARCHAR(75),
STATE VARCHAR(75)
);

CREATE TABLE VEHICLE_DETAILS(VEHICLE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
VEHICLE_NAME VARCHAR(100),
ADDRESS_ID INT,
CONSTRAINT fk_address FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS_DETAILS (ADDRESS_ID)
);

CREATE TABLE POLICY_DETAILS(POLICY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
POLICY_NAME VARCHAR(100),
VEHICLE_ID INT,
CONSTRAINT fk_vehicle  FOREIGN KEY (VEHICLE_ID) REFERENCES POLICY_DETAILS (VEHICLE_ID)
);


CREATE TABLE PARTY_DETAILS(PARTY_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
PARTY_NAME VARCHAR(100),
POLICY_ID INT,
CONSTRAINT fk_policy  FOREIGN KEY (POLICY_ID) REFERENCES POLICY_DETAILS (POLICY_ID)
);


select * from ADDRESS_DETAILS;
select * from VEHICLE_DETAILS;
select * from POLICY_DETAILS;
select * from PARTY_DETAILS;