apiVersion: v1
kind: Service
metadata:
   name: mysqlcompany
   labels:
     name: dbfrontend
spec:
   type: NodePort
   ports:
     - port: 3306
   selector:
     name: db
---
apiVersion: v1
kind: Pod
metadata:
  name: mysqlpod
  labels:
     name: db
spec:
    containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: MYSQL_DB
            value: mycompany
        ports:
          - containerPort: 3306
