apiVersion: v1
kind: Service
metadata:
  name: my-tomcatb
  labels:
    run: tomcat-business
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    run: tomcat-business
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-tomcatb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: tomcat-business
    spec:
      containers:
      - name: tomcat-business
        image: akd1234/userb:1.0
        ports:
        - containerPort: 8080
